### ISSUE TITLE
OnePage checkout

### ISSUE THREAD

**Issue by ferozsho** [HyperpayOpenSource/Opencart-3-Plugin-All#1]
Hi, 
the issue is on onepage checkout the "Pay Now" button and "Confirm Order" button both are separate functions.
1. if we click on Confirm Order button the data was saved but payment process not work
2. if we click on Pay Now the payment system works but customer data not work...
![Screenshot 2020-07-06 10 36 55](https://user-images.githubusercontent.com/4263848/86557732-b7dc4880-bf74-11ea-955f-259438884895.png)

**Comment by raaed-alharbi** [comment]
disable the onepage checkout. everything will work fine if you enable the hyperpay payment

**Comment by raaed-alharbi** [comment]
disable the onepage checkout. everything will work fine if you enable the hyperpay payment

**Comment by raaed-alharbi** [comment]
disable the onepage checkout. everything will work fine if you enable the hyperpay payment

**Comment by raaed-alharbi** [comment]
disable the onepage checkout. everything will work fine if you enable the hyperpay payment

**Comment by raaed-alharbi** [comment]
disable the onepage checkout. everything will work fine if you enable the hyperpay payment

**Comment by raaed-alharbi** [comment]
disable the onepage checkout. everything will work fine if you enable the hyperpay payment

**Comment by raaed-alharbi** [comment]
disable the onepage checkout. everything will work fine if you enable the hyperpay payment

**Comment by raaed-alharbi** [comment]
disable the onepage checkout. everything will work fine if you enable the hyperpay payment

**Comment by raaed-alharbi** [comment]
disable the onepage checkout. everything will work fine if you enable the hyperpay payment 

<a target="_blank" rel="noopener noreferrer" href="https://ibb.co/j4VJGPh"><img src="https://i.ibb.co/j4VJGPh/FDA2-F4-D7-A5-E8-40-CF-96-F1-A71-BB895650-C.jpg" alt="FDA2-F4-D7-A5-E8-40-CF-96-F1-A71-BB895650-C" style="max-width:100%;"></a>

**Comment by imodar** [comment]
> disable the onepage checkout. everything will work fine if you enable the hyperpay payment
> 
> [![FDA2-F4-D7-A5-E8-40-CF-96-F1-A71-BB895650-C](https://camo.githubusercontent.com/064a48c6804d5c423664518b1cba498b94ac8a6c/68747470733a2f2f692e6962622e636f2f6a34564a4750682f464441322d46342d44372d41352d45382d34302d43462d39362d46312d4137312d42423839353635302d432e6a7067)](https://ibb.co/j4VJGPh)

Disable an important plugin is not solving the problem.
I contact the team and they inform me that no way to solve it unless additional development.
HyperPay plugin is injecting all JS libraries at same time which is conflict maybe with theme, with quick check out .. etc.
Better to have a redirection payment method ( pay in a separate page like other payment gateways ) this will solve all conflicts
